# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: 2up/php7.2-cli:latest

# Select what we should cache between builds
cache:
  paths:
  - vendor/

before_script:
- apt-get install unzip
- composer self-update
- composer update

# Define pipeline stages
stages:
  - syntax
  - mess
  - test

phpcs:
  stage: syntax
  script:
    - ./vendor/bin/phpcs --error-severity=1 --warning-severity=8 --extensions=php
  only:
    refs:
      - master

phpmd:
  stage: mess
  script:
    - ./vendor/phpmd/phpmd/src/bin/phpmd src/ text _phpmd/rules.xml
  only:
    refs:
      - master
  allow_failure: true

php-7.2:
  stage: test
  script:
    - echo "$HIBP_API_KEY" > api.key
    - vendor/bin/phpunit --configuration phpunit.xml.dist --colors=never --coverage-text
  only:
    refs:
      - master

# Run our tests
# If Xdebug was installed you can generate a coverage report and see code coverage metrics.
#test:
#  script:
#  - vendor/bin/phpunit --configuration phpunit.xml.dist --colors=never --coverage-text
